import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Header } from '@/components/header';
import { Nav } from '@/components/nav';
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs';
import supabase from './config/supabaseClient';
import { cookies } from 'next/headers';
import { ProcessesProvider } from '@/context/processes';



const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'PJESIMP',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,

}: Readonly<{
  children: React.ReactNode;
}>) {
  
  //const client = createServerComponentClient({cookies: cookies});

  
  return (

    
    <html lang="pt-br">
      
      <body className={inter.className }  >
        <ProcessesProvider>
          <div className="bg-slate-100 min-h-screen">
            <Header/>
            <Nav/>
            {children}
          </div>
        </ProcessesProvider>
      </body>
    </html>
  );
}
